# Generated by Django 3.0.7 on 2020-07-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usr', models.CharField(default='none', max_length=200)),
                ('bet_type', models.IntegerField(blank=0, default=0, null=0)),
                ('bet_wager', models.IntegerField(blank=0, default=0, null=0)),
                ('bet_payout', models.IntegerField(blank=0, default=0, null=0)),
                ('bet_kills', models.IntegerField(blank=0, default=0, null=0)),
                ('bet_finish', models.IntegerField(blank=0, default=0, null=0)),
                ('bet_over_position', models.IntegerField(blank=0, default=0, null=0)),
                ('bet_over_kills', models.IntegerField(blank=0, default=0, null=0)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='ExecutedBet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_id', models.IntegerField(blank=0, default=0, null=0)),
                ('market_maker', models.CharField(default='none', max_length=200)),
                ('market_taker', models.CharField(default='none', max_length=200)),
            ],
        ),
    ]
