# Generated by Django 3.0.7 on 2020-07-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0002_match_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='match_id',
            field=models.IntegerField(blank=0, default=0, null=0),
        ),
    ]
