# Generated by Django 3.0.7 on 2020-07-21 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0003_bet_match_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='name',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
