# Generated by Django 3.0.7 on 2020-07-21 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0004_match_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stream',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='stream_id',
            new_name='streamer_id',
        ),
    ]
