# Generated by Django 3.0.7 on 2020-07-24 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0006_auto_20200721_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
