# Generated by Django 3.0.7 on 2020-07-24 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0008_auto_20200724_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
