# Generated by Django 3.0.7 on 2020-07-25 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0009_auto_20200724_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='executedbet',
            name='match_id',
            field=models.IntegerField(blank=0, default=0, null=0),
        ),
    ]
