# Generated by Django 3.0.7 on 2020-07-25 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0010_executedbet_match_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExecutedBet',
        ),
        migrations.AddField(
            model_name='bet',
            name='taker',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
