# Generated by Django 3.0.7 on 2020-07-29 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0011_auto_20200725_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='is_started',
            field=models.BooleanField(default=False),
        ),
    ]
