# Generated by Django 3.0.7 on 2020-07-29 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0012_bet_is_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='in_progress',
            field=models.BooleanField(default=False),
        ),
    ]
