# Generated by Django 3.0.7 on 2020-07-29 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0013_match_in_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
