# Generated by Django 3.0.7 on 2020-07-29 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0014_auto_20200729_0311'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bet',
            name='user_winner',
            field=models.BooleanField(default=False),
        ),
    ]
