# Generated by Django 3.0.7 on 2020-08-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0015_auto_20200729_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='streamer_name',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
