# Generated by Django 3.0.7 on 2020-07-24 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200721_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='coins',
            field=models.IntegerField(blank=0, default=0, null=0),
        ),
    ]
